---
title: "Exploring Salary Differences Among University of Nebraska Employees"
author: "Grant Cole, Madison Lane, Maria Pinkerton, Noah Polacek, Luis Rodriguez"
date: "Abstract Due: February 22, 2022"
output: pdf_document
hello
---

\abstract{The salaries of university employees vary significantly based on the following: experience, university size, and department. In particular, there are vast differences in salaries among faculty members and employees across departments, with professors in mathematical and business-related fields paid higher than their counterparts in humanities and fine arts, on average. Using a data file containing over 13,000 observations (each corresponding to a salaried instructor or staff member) from the University of Nebraska payroll from the 2021-2022 fiscal year, this poster contains salary relationships across departments, positions (assistant professor, associate professor, full professor), and universities. Through the use of exploratory data analysis, we seek to gain a more thorough understanding of professorial salaries within the University of Nebraska system.}

```{r, echo = FALSE}
library(dplyr, warn.conflicts = FALSE)
library(knitr)
Salary <- read.csv("https://raw.githubusercontent.com/noah-po/datavisualization/master/Data/Salary.csv")
unoSalary <- Salary %>% filter(Salary$Campus == "UNO")
unlSalary <- Salary %>% filter(Salary$Campus == "UNL")
unkSalary <- Salary %>% filter(Salary$Campus == "UNK")
uncaSalary <- Salary %>% filter(Salary$Campus == "UNCA")
unmcSalary <- Salary %>% filter(Salary$Campus == "UNMC")

Salary$Salary.from.Other.Funds <- NULL
Salary$Salary.from.State.Aided.Funds <- NULL
#Removing the two rightmost columns for UNO
unoSalary$Salary.from.Other.Funds <- NULL
unoSalary$Salary.from.State.Aided.Funds <- NULL
##for UNL...
unlSalary$Salary.from.Other.Funds <- NULL
unlSalary$Salary.from.State.Aided.Funds <- NULL
##for UNK...
unkSalary$Salary.from.Other.Funds <- NULL
unkSalary$Salary.from.State.Aided.Funds <- NULL
##for UNCA...
uncaSalary$Salary.from.Other.Funds <- NULL
uncaSalary$Salary.from.State.Aided.Funds <- NULL
##for UNMC...
unmcSalary$Salary.from.Other.Funds <- NULL
unmcSalary$Salary.from.State.Aided.Funds <- NULL

##Adding column names for each each college's dataset.
colnames(Salary) <- c("Employee","Position","Campus", "Department", "Budgeted Annual Salary")
colnames(unoSalary) <- c("Employee","Position","Campus", "Department", "Budgeted Annual Salary")
colnames(unlSalary) <- c("Employee","Position","Campus", "Department", "Budgeted Annual Salary")
colnames(unkSalary) <- c("Employee","Position","Campus", "Department", "Budgeted Annual Salary")
colnames(uncaSalary) <- c("Employee","Position","Campus", "Department", "Budgeted Annual Salary")
colnames(unmcSalary) <- c("Employee","Position","Campus", "Department", "Budgeted Annual Salary")

kable(head(Salary), format.args = list(big.mark = ","))
kable(head(unoSalary), format.args = list(big.mark = ","))
kable(head(unlSalary), format.args = list(big.mark = ","))
kable(head(unkSalary), format.args = list(big.mark = ","))
kable(head(uncaSalary), format.args = list(big.mark = ","))
kable(head(unmcSalary), format.args = list(big.mark = ","))

```
